apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  project: default

  source:
    chart: mysql
    repoURL: http://gitlab.amway-poc.com/sre/chart/mysql
    targetRevision: 1.16.1
    helm:
      releaseName: mysql
      parameters:
      - name: global.storageClass
        value: tanzu-storage-policy
      - name: image.tag
        value: 8.0.30-debian-11-r15
      - name: auth.username
        value: test
      - name: auth.password
        value: test

  destination:
    server: https://kubernetes.default.svc
    namespace: infra

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true