resources:
- application.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- virtualservice.yaml
- gateway.yaml
- destination-rule.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization