resources:
- application.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- virtualservice.yaml
- destination-rule.yaml

# configMapGenerator:
# - name: details
#   files:
#   - config/details.conf

# generatorOptions:
#   disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization